const intitialStory = [

	{
		name: "Joksin",
		character: "Joksin",
		location: "ApproachSenate",
		dialogue: "Guys! You made it!",
		type: "dialogue",
	},

	{
		name: "Joksin",
		character: "Joksin",
		location: "ApproachSenate",
		dialogue: "Welcome to the galactic senate, where decisions that affect the whole galaxy are made by people who sometimes know what they’re doing.",
		type: "dialogue",
	},

	{
		name: "Joksin",
		character: "Joksin",
		location: "ApproachSenate",
		dialogue: "Come on, quickly! The meeting is about to start! We have to show them earth isn’t empty, else they will blow it up.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "Ahh, Joksin Schura, I was just leaving, to what do i owe the honor?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Can it Hakaan, we know about the meeting, and we here to get you to back off Earth.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "What meeting? Oh the one about Snarfland? Ohoho we agreed to have that hours ago, we all agreed no one would miss the planet ‘Dirt’.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "You changed the meeting time?! You can’t just do that! How will we know when to protest?",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "Actually we just changed the times, so i would say we very much can.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "We thought, since it was such a controversial topic, we best move it to an unknown time to speed things up a bit - If you have any complaints you can send it to the senator’s office and they will hopefully get to it before the vote.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "Now if you will excuse me, I must go oversee a paint drying competition.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "AAARGGGH! That damn senator!!!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Okay, not the time to get angry, time to find solutions!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Hakaan said they still need to vote, that gives us a few days to make some people change their minds.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "The galactic senate has 5 members, right now they all want to destroy the earth, but if we can make 3 of them change their minds, we will have majority and Hakaan won’t be allowed to do anything.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "You guys stay right here and make a star map, I’ll be right back, just need to make some phonecalls!",
		type: "dialogue",
	},
	{
		name: "Starmap",
		character: "Joksin",
		location: "Senate",
		dialogue: "Hey guys sorry for running off so suddenly. I’m sending over some information about making a star map right now. First you must get a hologram screen, it should look a lot like human paper, then you just draw and glue on the different planets in the galaxy. When you’re done send a picture to mission control so they can give it the green light.",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Wow, that’s a great star map! Now let’s not waste any more time, we have a lot of galaxy to travel, and not a lot of time to do it!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "TO ETHERIA 13!!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "The Rose of Etheria 13 is an artist collective - thats a fancy word for a bunch of people living together - with their main base on Etheria 13. If we are going to make them side with us to save earth, we will need to show them some human art.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Morkaas",
		location: "Etheria",
		dialogue: "Their leader Morkaas used to be a soldier, but he retired to become a painter and dancer. He makes the big decisions around here, but he makes them based on what the people wants.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Morkaas",
		location: "Etheria",
		dialogue: "Before you ask, no there are no other Etheria’s they just made it number 13 to sound cool.",
		type: "dialogue",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		location: "Etheria",
		dialogue: "Please leave, I have no time for uncultured life forms.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "But...",
		type: "dialogue",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		location: "Etheria",
		dialogue: "No but’s begone, I must not be disturbed while I’m watching space factor.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Uggghhhh, I swear if all the senators are like this, i will...",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Kick something...",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Very hard!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "And it's going to break!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Okay back to the drawing board. He said he was going to watch ‘space factor’ right? Well let’s make our own space factor, so he can watch you perform there.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "EtheriaTheater",
		dialogue: "First you guys have to build a scene though. Why are you looking at me like that? Isn’t that how talent shows work on earth? You guys are weird.",
		type: "dialogue",
	},
	{
		name: "Make a Scene",
		character: "Joksin",
		location: "EtheriaTheater",
		dialogue: "We’ve arrived on Etheria 13, but Morkaas won’t give us the time of day, we have to convince him earth is worth saving! You need to build a scene where you can perform some human art for Morkaas and the rest of Etheria 13. When you’re done building the scene, make sure to send a picture to mission control so we know that it passes inspection! Good luck!",
		type: "mission",
	},
	{
		name: "Space Factor",
		character: "Joksin",
		location: "EtheriaTheater",
		dialogue: "Great job with the scene, look: people are already coming to watch. Now you have to show off your skills. Morkaas is going to get his fuzzy socks blown off!. Take some time to prepare your performance, then show everybody how good humans are at art. Remember to record it to save for the future!",
		type: "mission",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		location: "EtheriaTheater",
		dialogue: "Wow! I had no idea Humans could do any of those things! Hakaan has been lying about your planet. I promise I will do everything in my poweer to protect your people!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "EtheriaTheater",
		dialogue: "After your amazing performance on space factor, you are now stars to the Rose of Etheria 13. Morkaas has made it his highest goal to save the earth, and he will let nothing stand in his way to accomplish it.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Sandena",
		dialogue: "Next stop is Sandena, home of the Kay’Li.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Selena",
		location: "Sandena",
		dialogue: "The Kay’Li love biology and farming, but a few years ago they lost their great knowledge base in a mysterious accident, and now have to buy food from the Hakaan’s people, The Combine Supremacy to survive.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Selena",
		location: "Sandena",
		dialogue: "Selena actually wants to save earth, but if she doesn’t vote the way Hakaan says she won’t be able to feed her people.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Sandena",
		dialogue: "Luckily you humans are great farmers though! Right? So maybe you can show the Kay’Li some tricks, they won’t have to rely on Hakaan for food and can vote as they want.",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "Hey it’s great you’re here, but I’m really busy, do you think you could return in uhm… 8 weeks?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "No please, this is really important!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "She… just ran off…",
		type: "dialogue",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "Hey guys, sorry about Selena, she didn’t use to be like this, but she’s  trying to fix everything for everyone, and well, she only has 2 hands. I’m Mirabeli, her assistant, maybe i can be of assistance?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "We heard about your problems with farming and we have come to help!",
		type: "dialogue",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "Oh yes, such a terrible affair, as you can see we can barely grow anything, and even with help from those bastards at The Combine Supremacy, people are barely getting by. If only there was something we could do",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "There is! You can let these humans teach you their knowledge of farming. Then maybe to pay them back you could vote not to blow up their planet.",
		type: "dialogue",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "That would be splendid!! Please teach us your ways humans. I will make sure to pass it all along to Selena.",
		type: "dialogue",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "Hello again! Sorry Selena couldn’t be here, she’s been really busy lately. But Joksin tells me you can help with that? Humans are really good at farming right? Can you show us some of it? And please take some pictures that we can use in our new knowledge bank.Thank you so much",
		type: "Mission",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "That’s amazing! I have to tell Selena, be right back! Don’t move a muscle!",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "The fields… They’re, they’re growing! Did you do this humans?!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "They did! Isn’t it great? Such a clever species definitely deserve to be protected right?",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "With plants once again growing on Sandena, the Kay’li are no longer forced to rely on Hakaan to give them enough food to survive. Selena is now free to vote to save the earth, and you now have 2 of the 3 groups you need on your side! This is unfortunately also the end of the test version, so what happens next, that is for you to decide. With plants once again growing on Sandena, the Kay’li are no longer forced to rely on Hakaan to give them enough food to survive. Selena is now free to vote to save the earth, and you now have 2 of the 3 groups you need on your side! This is unfortunately also the end of the test version, so what happens next, that is for you to decide.",
		type: "mission",
	},
];

export default intitialStory;
