const intitialStory = [

	{
		name: "Joksin",
		character: "Joksin",
		location: "ApproachSenate",
		dialogue: "Jongens! Jullie hebben het gehaald!",
		type: "dialogue",
	},

	{
		name: "Joksin",
		character: "Joksin",
		location: "ApproachSenate",
		dialogue: "Welkom bij de Galactische Senaat. Hier worden beslissingen gemaakt die invloed hebben op de gehele melkweg door mensen die soms weten wat ze doen.",
		type: "dialogue",
	},

	{
		name: "Joksin",
		character: "Joksin",
		location: "ApproachSenate",
		dialogue: "Kom snel! De vergadering gaat beginnen! Wij moeten ze laten zien dat de aarde niet een verlaten planeet is, want anders blazen zij het op!",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "Ah, Joksin Schura, ik stond op het punt te vertrekken, aan wie heb ik het genoegen?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Hou op Hakaan, wij weten over de vergadering en wij gaan er voor zorgen dat jij de aarde met rust laat!",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "Welke vergadering? Oh, die over Snarfland? Ohoho, wij zijn het er met zijn allen over eens geworden dat niemand die 'troep' zal missen als het weg is.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Je hebt de geplande tijd van de vergadering aangepast?! Dat kunnen je niet zomaar doen! Hoe moesten wij dit weten?",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "Je ziet het toch, de tijd was aangepast dus kennelijk kunnen wij dat zomaar wel doen.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "We gaan binnenkort erover stemmen, dus als je klachten hebt, kun je die naar het kantoor van de senator sturen.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		location: "Senate",
		dialogue: "Als je me nu wilt excuseren, ik moet namelijk toezicht houden op een verfdroogwedstrijd",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "AAARGGGH! Die sluwe senator!!!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Okay, het is nu niet de tijd om boos te worden. We moeten naar oplossingen zoeken!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Hakaan zei dat ze nog moesten stemmen. Dat geeft ons dus een paar dagen de tijd om de andere leden te overtuigen dat de aarde niet opgeblazen moet worden!",
		type: "dialogue",
		breakpoint: true,
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "De Galactische Senaat heeft 5 leden. Op dit moment willen ze allemaal de aarde vernietigen, maar als we 3 van hen van gedachten kunnen doen veranderen, zullen we de meerderheid hebben. Hakaan zal dan zijn duistere plannen moeten staken.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Blijven jullie hier om een sterrenkaart te maken.! Ik ben zo terug! Ik moet namelijk eerst nog wat telefoontjes plegen!",
		type: "dialogue",
	},
	{
		name: "Sterrenkaart",
		character: "Joksin",
		location: "Senate",
		dialogue: "Hey jongens, sorry dat ik zo plotseling ben weggelopen. Ik stuur jullie nu wat informatie over het maken van een sterrenkaart. Eerst moeten jullie een hologramscherm pakken. Het zou veel op papier moeten lijken. Vervolgens moeten jullie daarop de verschillende planeten in de Melkweg tekenen en lijmen om ze met elkaar te verbinden en een overzicht te creëren. Als je klaar bent stuur dan een foto naar missiecontrole zodat zij het kunnen controleren.",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "Wauw, dat is een geweldige sterrenkaart! Laten we nu geen tijd meer verspillen, we hebben veel melkwegreizen op de planning staan en niet veel tijd!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Senate",
		dialogue: "NAAR ETHERIA 13!!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "De Roos van Eteria 13 is een kunstenaars collectief – dat is een duur woord voor een aantal samenlevende mensen – met hun hoofdbasis op Eteria 13. Als we er voor willen zorgen dat ze aan onze kant staan dan moeten we ze wat indrukwekkende menselijk kunststukken laten zien.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Morkaas",
		location: "Etheria",
		dialogue: "Hun leider Morkaas was een soldaat, maar hij ging met pensioen om schilder en danser te worden. Hij neemt de grote beslissingen hier, maar hij maakt ze gebaseerd op wat de bewoners willen.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Morkaas",
		location: "Etheria",
		dialogue: "Voordat jullie  het vragen, nee, er zijn geen andere Eteria’s. Ze hebben het nummer 13 genoemd omdat het simpelweg cool staat.",
		type: "dialogue",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		location: "Etheria",
		dialogue: "Ga alsjeblieft weg. Ik heb geen tijd voor onbeschaafde levensvormen.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Maar...",
		type: "dialogue",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		location: "Etheria",
		dialogue: "Geen gemaar, ga weg. Ik dien niet gestoord te worden wanneer ik naar Ruimte Factor kijk.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Uggghhhh, als alle senatoren zo zijn, dan zal ik…",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Iets schoppen...",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Heel hard!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "En dan gaat het kapot!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Etheria",
		dialogue: "Oké terug naar de tekentafel. Hij zei dat hij Ruimte Factor zou gaan kijken toch? Laten we een eigen Ruimte Factor maken zodat hij jullie daar kan zien optreden!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "EtheriaTheater",
		dialogue: "Eerst moeten jullie een scène bouwen. Waarom kijken jullie me zo aan? Is dat niet hoe een talentenjacht werkt op aarde? Jullie zijn vreemder dan ik dacht..",
		type: "dialogue",
	},
	{
		name: "Maaak een scène",
		character: "Joksin",
		location: "EtheriaTheater",
		dialogue: "We zijn gearriveerd op Etheria 13, maar Morkaas geeft ons niet de tijd van de dag. We moeten hem ervan overtuigen dat de aarde het redden waard is! Jullie moeten een scène bouwen waarin jullie wat menselijke kunst kunt uitvoeren voor Morkaas en de rest van Etheria 13. Als jullie klaar zijn met het bouwen van een scène, zorg er dan voor dat jullie een foto sturen naar missiecontrole. Succes!",
		type: "mission",
	},
	{
		name: "Space Factor",
		character: "Joksin",
		location: "EtheriaTheater",
		dialogue: "Goed gedaan met de scène! Kijk de mensen zijn nieuwsgierig en komen naar jullie kijken! Nu moeten jullie wat menselijke vaardigheden laten zien. We gaan de Morkaas helemaal omver blazen! Neem de tijd om jullie optreden voor te bereiden en laat iedereen van Eteria 13 zien hoe goed mensen zijn in kunst! Vergeet niet om het op te nemen, zodat je het later terug kan kijken!",
		type: "mission",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		location: "EtheriaTheater",
		dialogue: "Wauw! Ik had geen idee dat de mensen van de aarde dat soort dingen konden doen! Hakaan heeft gelogen over jullie planeet! Ik beloof dat ik alles zal doen wat ik kan om jullie te beschermen!",
		type: "dialogue",
		breakpoint: true,
	},
	{
		name: "Overwinning",
		character: "Morkaas",
		location: "EtheriaTheater",
		dialogue: "Na jullie geweldig prestatie op Ruimte Factor zijn jullie beroemdheden geworden op De Roos van Eteria 13. Morkaas zal ervoor zorgen dat hij zijn best doet om de aarde te redden!",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Sandena",
		dialogue: "De volgende halte is Sandena, de leefomgeving van De Kayli.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Selena",
		location: "Sandena",
		dialogue: "De Kayli houden van biologie en landbouw, maar een paar jaar geleden verloren ze hun grote kennis in een mysterieus ongeluk. Tegenwoordig kopen zij hun eten van de planeet van die vreselijke Hakaan, De Verenigde Heerschappij, om te overleven.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Selena",
		location: "Sandena",
		dialogue: "Selena wil eigenlijk de aarde wel redden, maar als ze niet stemt zoals Hakaan zegt dan zal het volk er onder gaan lijden. Hakaan zal dan zeker geen eten meer verkopen aan De Kayli..",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "Sandena",
		dialogue: "Gelukkig zijn jullie mensen echter geweldige boeren! Toch? Dus misschien kunnen jullie De Kayli wat trucjes laten zien zodat ze niet op Hakaan hoeven te vertrouwen voor eten en zodat zij kunnen stemmen zoals zij zelf graag willen.",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "Hey! Fantastisch dat je hier bent maar ik ben momenteel heel erg druk. Kun je terug komen over uhm… 8 weken?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Alsjeblieft, dit is heel belangrijk!!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Ze liep.. gewoon weg..",
		type: "dialogue",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "Hey jongens, sorry voor het gedrag van Selena, Vroeger was zij nooit zo maar ze probeert alles in orde te maken voor iedereen en ze heeft maar 2 handen. Ik ben haar assistent, Mirabeli. Misschien kan ik jullie verder op weg helpen?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Wij hebben gehoord over jullie problemen met landbouw en zijn hier om jullie te helpen!",
		type: "dialogue",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "Dat klopt.. Zoals je ziet kunnen we nauwelijks iets groeien en zelfs met de hulp van die achterbakse mensen van De Verenigde Heerschappij komen mensen amper rond. Was er maar iets dat wij konden doen.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Jullie kunnen ook iets doen! Deze mensen kunnen jullie kennis bijbrengen over landbouw zodat jullie zelf eten kunnen oogsten. Het enige wat wij terug vragen is een stem van jullie om de aarde te beschermen ",
		type: "dialogue",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "Dat zou geweldig zijn! Vertel ons alsjeblieft hoe het moet. Ik zal er dan voor zorgen dat alles bij Selena terecht komt.",
		type: "dialogue",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "Sorry Selena kon hier niet zijn. Ze is de laatste tijd erg druk geweest. Maar Joksin zei dat jullie mij daarmee kunnen helpen? Mensen zijn echt goed in landbouw toch? Kun je ons er wat van laten zien? En maak alsjeblieft een paar foto’s die we kunnen gebruiken in onze nieuw kennisbank. Heel erg bedankt!",
		type: "mission",
	},
	{
		name: "Mirabeli",
		character: "Mirabeli",
		location: "SandenaSettlement",
		dialogue: "Dat is ongelofelijk! Dit moet Selena weten en zien! Wacht, ik ben zo terug!",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "De velden… ze zijn.. ze zijn aan het groeien!! Hebben jullie dit gedaan aardelingen?!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Dat hebben zij zeker! Is het niet geweldig? Een slim soort als dit moet toch zeker bescherm worden?",
		type: "dialogue",
    },
    {
		name: "Selena",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "Absoluut, geef me een moment om mijn spullen in te pakken. Ik ga terug naar het senaat om ze een stuk van mijn verstand te geven.",
		type: "dialogue",
    },
	{
		name: "Selena",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "Nu de planten weer op Sandena groeien hoeven de Kayli niet langer op Hakaan te vertrouwen om hen voldoende voedsel te geven om te kunnen overleven. Selena is nu vrij om te stemmen om de aarde te redden en dat bekenent dat je nu 2 van de 3 groepen benodigde groepen aan jouw zijde hebt! Dit is helaas ook het einde van de testversie. Wat er gaat gebeuren in de toekomst? Dat bepaal jij.",
		type: "mission",
	},
];

export default intitialStory;
