const intitialStory = [


	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "ApproachSenate",
		dialogue: "Geweldig! Jullie hebben het gehaald!",
		type: "dialogue",
	},

	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "ApproachSenate",
		dialogue: "Welkom bij de Galactische Senaat!",
		type: "dialogue",
	},

	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "ApproachSenate",
		dialogue: "Hier worden beslissingen gemaakt die invloed hebben op de gehele melkweg!",
		type: "dialogue",
	},

	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "ApproachSenate",
		dialogue: "Door personen die denken dat ze er verstand van hebben!",
		type: "dialogue",
	},

	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "ApproachSenate",
		dialogue: "Kom snel! De vergadering gaat beginnen!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "ApproachSenate",
		dialogue: "Wij moeten ze laten zien dat de aarde niet een verlaten planeet is, want anders blazen zij het op!",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "Joksin",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Ah, Joksin Schura, ik stond op het punt te vertrekken, wat is de reden van jouw bezoek?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "Hakaan",
		sidecharacter: "Hakaan",
		location: "Senate",
		dialogue: "Hou op Hakaan, wij weten over de vergadering en wij gaan er voor zorgen dat jij de aarde met rust laat!",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "Joksin",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Welke vergadering?",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "Joksin",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Oh, die over Snarfland? We hebben dat een uur geleden allang besloten.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "Joksin",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Ohoho, wij zijn het er met zijn allen over eens geworden dat niemand die 'troep' zal missen als het weg is.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "Hakaan",
		sidecharacter: "Hakaan",
		location: "Senate",
		dialogue: "Je hebt de geplande tijd van de vergadering aangepast?! Dat kunnen jullie niet zomaar doen! Hoe moesten wij dat weten?",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "Joksin",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Je ziet het toch, de tijd was aangepast dus kennelijk kunnen wij dat zomaar wel doen.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "Joksin",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Als je me nu wilt excuseren, ik moet namelijk toezicht houden op een verfdroogwedstrijd.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "AAARGGGH! Die sluwe senator!!!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Okay, het is nu niet de tijd om boos te worden. We moeten naar oplossingen zoeken!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Ik weet dat ze nog moeten stemmen. Dat geeft ons dus een paar dagen de tijd om de andere leden te overtuigen dat de aarde niet opgeblazen moet worden!",
		type: "dialogue",
		breakpoint: true,
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Als ze dan allemaal voor de aarde gaan stemmen, is de aarde gered!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "De Galactische Senaat heeft 5 leden. Op dit moment willen ze allemaal de aarde vernietigen.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Maar als we 3 van hen overtuigen dat de aarde eigenlijk super tof is, dan hebben we de meerderheid!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "En dan is de aarde gered!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Geef me even een minuutje! Ik moet namelijk eerst nog wat telefoontjes plegen!",
		type: "dialogue",
	},
	{
		name: "Sterrenkaart",
		character: "Joksin",
		location: "Senate",
		dialogue: "Hallo allemaal, sorry dat ik zo plotseling ben weggelopen. Ik stuur jullie nu wat informatie over het maken van een sterrenkaart. Eerst moeten jullie een hologramscherm pakken. Het zou veel op papier moeten lijken, daarna kunnen jullie de planeten erop tekenen en lijmen zodat het lijkt op een melkweg. Als jullie klaar zijn, maak er dan een toffe foto van!",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Wauw, dat is een geweldige sterrenkaart!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Laten we nu geen tijd meer verspillen, we hebben veel melkwegreizen op de planning staan en niet veel tijd!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "NAAR ETERIA 13!!",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroRose",
		dialogue: "De Roos van Eteria 13 is een kunstenaars collectief, dat is een duur woord voor een aantal samenlevende mensen.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroRose",
		dialogue: "Met hun hoofdbasis op Eteria 13.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroRose",
		dialogue: "Als we er voor willen zorgen dat ze aan onze kant staan dan moeten we ze wat indrukwekkende menselijk kunststukken laten zien.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroRose",
		dialogue: "Hun leider Morkaas was een soldaat, maar hij ging met pensioen om schilder en danser te worden.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroRose",
		dialogue: "Hij neemt de grote beslissingen hier, maar hij maakt ze samen met de bewoners van de planeet.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroRose",
		dialogue: "Voordat jullie  het vragen, nee, er zijn geen andere Eteria’s. Ze hebben het nummer 13 genoemd omdat het simpelweg cool staat.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		sidename: "none",
		sidecharacter: "none",
		location: "Etheria",
		dialogue: "Ga alsjeblieft weg. Ik heb geen tijd voor onbeschaafde levensvormen.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "Morkaas",
		sidecharacter: "Morkaas",
		location: "Etheria",
		dialogue: "Maar...",
		type: "dialogue",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		sidename: "Joksin",
		sidecharacter: "Joksin",
		location: "Etheria",
		dialogue: "Geen gemaar, ga weg. Ik dien niet gestoord te worden wanneer ik naar Space Got Talent kijk.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Etheria",
		dialogue: "Uggghhhh, als alle senatoren zo zijn, dan zal ik…",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Etheria",
		dialogue: "Iets schoppen...",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Etheria",
		dialogue: "Heel hard!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Etheria",
		dialogue: "En dan gaat het kapot!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Etheria",
		dialogue: "Oké terug naar de tekentafel. Hij zei dat hij Space Got Talent zou gaan kijken toch? Laten we een eigen Space Got Talent maken zodat hij jullie daar kan zien optreden!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "EtheriaTheater",
		dialogue: "Eerst moeten jullie een scène bouwen. Waarom kijken jullie me zo aan? Is dat niet hoe een talentenjacht werkt op aarde? Jullie zijn vreemder dan ik dacht...",
		type: "dialogue",
	},
	{
		name: "Space Got Talent",
		character: "Joksin",
		location: "EtheriaTheater",
		dialogue: "Als Morkaas niet naar ons gaat luisteren, moeten we iets doen om indruk te maken. We moeten hem ervan overtuigen dat de aarde het redden waard is! Laten we een podium maken en onze eigen talenten laten zien! Succes!",
		type: "mission",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		sidename: "none",
		sidecharacter: "none",
		location: "EtheriaTheater",
		dialogue: "Wauw! Ik had geen idee dat de mensen van de aarde dat soort dingen konden doen! Hakaan heeft gelogen over jullie planeet! Ik beloof dat ik alles zal doen wat ik kan om jullie te beschermen!",
		type: "dialogue",
		breakpoint: true,
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "EtheriaTheater",
		dialogue: "De volgende halte is Sandena, de leefomgeving van De Kayli.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroKayli",
		dialogue: "De Kayli houden van biologie en landbouw, maar een paar jaar geleden verloren ze hun grote kennis in een mysterieus ongeluk. Tegenwoordig kopen zij hun eten van de planeet van die vreselijke Hakaan, De Verenigde Heerschappij, om te overleven.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroKayli",
		dialogue: "Selena wil eigenlijk de aarde wel redden, maar als ze niet stemt zoals Hakaan zegt dan zal het volk er onder gaan lijden. Hakaan zal dan zeker geen eten meer verkopen aan De Kayli..",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "IntroKayli",
		dialogue: "Gelukkig zijn jullie mensen echter geweldige boeren! Toch? Dus misschien kunnen jullie De Kayli wat trucjes laten zien zodat ze niet op Hakaan hoeven te vertrouwen voor eten en zodat zij kunnen stemmen zoals zij zelf graag willen.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "Selena",
		character: "Selena",
		sidename: "none",
		sidecharacter: "none",
		location: "SandenaSettlement",
		dialogue: "Hey! Fantastisch dat je hier bent maar ik ben momenteel heel erg druk. Kun je terug komen over uhm… 8 weken?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Selena",
		location: "SandenaSettlement",
		dialogue: "Alsjeblieft, dit is heel belangrijk!!",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Okay, maar praat snel, ik heb niet zoveel tijd!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Selena",
		location: "SandenaSettlement",
		dialogue: "We hebben gehoord van de problemen die jullie hebben met jullie landbouw en we zijn hier om te helpen!",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Zijn dit mensen van aarde? Het spijt me van jullie planeet, kan er niks meer aan veranderen helaas.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Selena",
		location: "SandenaSettlement",
		dialogue: "Dat kan je wel! Ze kunnen je hun wijsheid over landbouw vertellen, en dan misschien kan je hen helpen met het niet opblazen van de aarde!",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Dat zou geweldig zijn! Natuurlijk zullen we jullie dan helpen!",
		type: "dialogue",
	},
	{
		name: "Groene vingers",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "Joksin vertelde dat jullie ons kunnen helpen met onze landbouw? Aardlingen zijn goed met landbouw toch? Kan je dat laten zien? Neem ook wat foto's er van, zodat wij het kunnen opslaan in onze Kennisbank. Heel erg bedankt!",
		type: "mission",
	},
	{
		name: "Selena",
		character: "Selena",
		sidename: "none",
		sidecharacter: "none",
		location: "SandenaSettlement",
		dialogue: "De velden… ze zijn.. ze zijn aan het groeien!! Hebben jullie dit gedaan aardelingen?!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "Selena",
		sidecharacter: "Selena",
		location: "SandenaSettlement",
		dialogue: "Dat hebben zij zeker! Is het niet geweldig? Een slim soort als dit moet toch zeker bescherm worden?",
		type: "dialogue",
    },
    {
		name: "Selena",
		character: "Selena",
		sidename: "Joksin",
		sidecharacter: "Joksin",
		location: "SandenaSettlement",
		dialogue: "Absoluut, geef me een moment om mijn spullen in te pakken. Ik ga terug naar het senaat om ze een stuk van mijn verstand te geven.",
		type: "dialogue",
    },
	{
		name: "Kookfestijn",
		character: "Selena",
		location: "SandenaSettlement",
		dialogue: "Ik kan je niet genoeg bedanken voor je hulp bij de landbouw. We maken een feest om het te vieren, wil je ons helpen met het koken?",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "SandenaSettlement",
		dialogue: "De laatste groep die we moeten overtuigen is De Torla!",
		type: "dialogue",
    },
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Vulcanus",
		dialogue: "De Torla houden van geschiedenis, vooral hun eigen geschiedenis.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Vulcanus",
		dialogue: "Zij hebben dan ook hun thuisplaneet verwoest, Vulcanus.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Vulcanus",
		dialogue: "Vlak daarna vonden zijn een nieuwe Vulcanus, maar… die hebben ze ook verwoest.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Vulcanus",
		dialogue: "Nu leven zij vrolijk op Vulcanus 7.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Vulcanus",
		dialogue: "Hun leider Areos ziet zichzelf als de held van de sterrenweg, echter doet hij nooit iets in het belang van anderen.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Areos is laat. Hij zou hier allang moeten zijn!",
		type: "dialogue",
	},
	{
		name: "Li-Lu",
		character: "Joksin",
		location: "Senate",
		dialogue: "Jeetje, de senator schiet niet echt op! Willen jullie een potje Li-Lu spelen terwijl we wachten? Wacht, hebben jullie nog nooit Li-Lu gespeeld? Echt niet? Dan zal ik het jullie even snel leren!",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "Senate",
		dialogue: "Daar ben je! Waarom ben je zo laat?",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "En wie ben jij? Hoe durf je zo tegen mij te praten?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "Senate",
		dialogue: "Mijn naam is Joksin Schura, en dit zijn de mensen van aarde.",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Dus?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "Senate",
		dialogue: "Hallo!? We hebben een afspraak gepland om de aarde te redden!",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Ik wil er niks meer over horen!",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Sterker nog, ik heb nu al helemaal geen behoefte meer om de aarde te redden!",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "De aarde is een stomme planeet, vol met stomme mensen! Wie heeft de naam ‘mensen’ überhaupt bedacht!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "Senate",
		dialogue: "KOM OP ZEG! Er moet toch iets zijn wat we kunnen doen om jou over te halen?",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "Senate",
		dialogue: "We stoppen niet met jou te irriteren voordat je luistert!",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Okay dan! De Soepkom van Vulcanus 5.",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Als jullie De Soepkom van Vulcanus 5 naar mij brengen dan zal ik voor het behoud van die stomme aarde van jullie stemmen.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "Senate",
		dialogue: "Dankje! Wacht, wat is De Soepkom van Vulcanus 5?",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Het is een eeuwenoude soepkom gemaakt door onze verre voorouders.",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "We hebben het achtergelaten in een kluis op Vulcanus 5.",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Succes! En nog een tip, ik zou de lava niet aanraken als ik jullie was.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Aaaarh, die senatoren! Nou ja, op naar Vulcanus 5!",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "VulcanusBase",
		dialogue: "Aha, dus dit is Vulcanus 5!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "VulcanusBase",
		dialogue: "Ze moeten echt stoppen met het ‘Vulcanus’ te noemen nadat de eerste 3 vulkanen zijn geworden.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "VulcanusBase",
		dialogue: "Dat vraagt naar problemen.",
		type: "dialogue",
	},
	{
		name: "De vloer is lava",
		character: "Joksin",
		location: "VulcanusBase",
		dialogue: "Oké, nu moeten we naar die kluis zien te komen! We moeten gewoon deze rivier van gesmolten lava oversteken, makkie toch?!",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "VulcanusVault",
		dialogue: "Okay, alles verloopt nog zoals gepland. Ik kan de kluis al zien!",
		type: "dialogue",
	},
	{
		name: "De kluis",
		character: "Joksin",
		location: "VulcanusBase",
		dialogue: "Natuurlijk zetten de oude Torlans een slot op de kluis, het was niet genoeg dat we een meer van gesmolten lava moesten oversteken. Gelukkig heb ik een ontcijferaar meegenomen, laat me hem gewoon op je tablet laden. Zodra je het hebt opgelost, laat je het zien aan de missie controle zodat zij het kunnen goedkeuren.",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "VulcanusVault",
		dialogue: "Wow, dat is echt geweldig. Ik bedoel, voor de Torlans dan..",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "VulcanusVault",
		dialogue: "Wacht is even, waarom staan er 3 kommen? Er hoort er maar een te zijn!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "VulcanusVault",
		dialogue: "Twee daarvan moeten nep zijn!",
		type: "dialogue",
	},
	{
		name: "Soep Experiment",
		character: "Joksin",
		location: "VulcanusVault",
		dialogue: "De Soepkom van Vulcanus 5 is in zicht, nu moeten we de juiste vinden! Maak wat testvloeistof en giet het in 3 verschillende doorzichtige schaaltjes, bij de neppe zal de kleur van de vloeistof veranderen. Neem een leuke foto van het resultaat wanneer je klaar bent.",
		type: "mission",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "VulcanusVault",
		dialogue: "Fantastisch! Laten we terug gaan zodat we het aan Areos kunnen laten zien.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "SenateApproach",
		dialogue: "Areos, we hebben die soepkom van je. Nu jouw kant van de belofte.",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "SenateApproach",
		dialogue: "Onmogelijk!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "SenateApproach",
		dialogue: "Toch wel mogelijk!",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "SenateApproach",
		dialogue: "Maar... Hoe heb je...!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "SenateApproach",
		dialogue: "Wij hebben gedaan waar jij om vroeg.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "SenateApproach",
		dialogue: "We moesten over een zee van lava, een oud slot kraken en de wetenschap inschakelen om de echte schaal te vinden.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Areos",
		location: "SenateApproach",
		dialogue: "Je moet de aarde nu wel helpen!",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "SenateApproach",
		dialogue: "Oke, goed dan. Ik help jullie.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Space",
		dialogue: "",
		type: "transition",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Sjaksjok van R.I.T.A. kan vandaag niet aanwezig zijn.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Zij heeft gestemd voor de vernietiging van De Aarde.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Hakaan van De Verenigde Heerschappij, waar stem jij voor?",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Ik stem voor het vernietigen van de aarde!",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Morkaas van De Roos van Etheria 13, waar stem jij voor?",
		type: "dialogue",
	},
	{
		name: "Morkaas",
		character: "Morkaas",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Ik stem voor het behoud van de aarde!",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Selena van de Kayli, waar stem jij voor?",
		type: "dialogue",
	},
	{
		name: "Selena",
		character: "Selena",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Ik stem ook voor het behoud van de aarde!",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Areos van de Torla, waar stem jij voor?",
		type: "dialogue",
	},
	{
		name: "Areos",
		character: "Areos",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Ugh, kennelijk voor het behoud van de aarde...",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Iedereen heeft gestemd.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "De gegevens worden verwerkt.",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "...",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "DING",
		type: "dialogue",
	},
	{
		name: "none",
		character: "none",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "De aarde zal blijven bestaan.",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "Hakaan",
		location: "Senate",
		dialogue: "Ha, je hoort het jij stom insect!",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "Lach maar, dit is niet het laatste wat je van mij hoort.",
		type: "dialogue",
	},
	{
		name: "Hakaan",
		character: "Hakaan",
		sidename: "none",
		sidecharacter: "Joksin",
		location: "Senate",
		dialogue: "MUAHAHAHAHAHA",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Verdwijn!",
		type: "dialogue",
	},
	{
		name: "Joksin",
		character: "Joksin",
		sidename: "none",
		sidecharacter: "none",
		location: "Senate",
		dialogue: "Geweldig! Het is jullie gelukt! De aarde is veilig!",
		type: "dialogue",
	},
	{
		name: "Einde",
		character: "Joksin",
		location: "Senate",
		dialogue: "Goed gedaan, door jou is de aarde veilig! Bedankt voor het spelen! Family Quest Team",
		type: "mission",
	},

];

export default intitialStory;
